# Generated by Django 2.1.3 on 2018-12-10 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0003_auto_20181210_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_visitor',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 96128)),
        ),
        migrations.AlterField(
            model_name='add_visitor',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 96198)),
        ),
        migrations.AlterField(
            model_name='attendence_tracker',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 110527)),
        ),
        migrations.AlterField(
            model_name='attendence_tracker',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 110574)),
        ),
        migrations.AlterField(
            model_name='attendence_tracker',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 110638)),
        ),
        migrations.AlterField(
            model_name='book_cab_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 105195)),
        ),
        migrations.AlterField(
            model_name='book_cab_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 105263)),
        ),
        migrations.AlterField(
            model_name='book_cab_details',
            name='time_of_depature',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 105150), null=True),
        ),
        migrations.AlterField(
            model_name='bring_groceries',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 107319)),
        ),
        migrations.AlterField(
            model_name='bring_groceries',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 107389)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 109625)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 109692)),
        ),
        migrations.AlterField(
            model_name='cooking',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 103501)),
        ),
        migrations.AlterField(
            model_name='cooking',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 103569)),
        ),
        migrations.AlterField(
            model_name='faculty_service_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 102009)),
        ),
        migrations.AlterField(
            model_name='faculty_service_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 102079)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 97081)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 97142)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 96952)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 96991)),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 95132)),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 95201)),
        ),
        migrations.AlterField(
            model_name='laundry_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 99822)),
        ),
        migrations.AlterField(
            model_name='laundry_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 99890)),
        ),
        migrations.AlterField(
            model_name='medical_sevices',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 108419)),
        ),
        migrations.AlterField(
            model_name='medical_sevices',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 108524)),
        ),
        migrations.AlterField(
            model_name='notify_gate',
            name='date_of_arrival',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 106192)),
        ),
        migrations.AlterField(
            model_name='notify_gate',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 106282)),
        ),
        migrations.AlterField(
            model_name='notify_gate',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 106348)),
        ),
        migrations.AlterField(
            model_name='student_service_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 98345)),
        ),
        migrations.AlterField(
            model_name='student_service_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 98405)),
        ),
        migrations.AlterField(
            model_name='student_service_details',
            name='work_completed_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 98290)),
        ),
        migrations.AlterField(
            model_name='student_service_details',
            name='worker_assigned_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 98251)),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 68423)),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 68574)),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 93975)),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 94059)),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 111478)),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 111542)),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 111376)),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 43, 9, 111440)),
        ),
    ]
