# Generated by Django 2.1.3 on 2018-12-10 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0007_auto_20181210_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_visitor',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 376669)),
        ),
        migrations.AlterField(
            model_name='add_visitor',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 376737)),
        ),
        migrations.AlterField(
            model_name='attendence_tracker',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 390200)),
        ),
        migrations.AlterField(
            model_name='attendence_tracker',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 390268)),
        ),
        migrations.AlterField(
            model_name='attendence_tracker',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 390360)),
        ),
        migrations.AlterField(
            model_name='book_cab_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 384034)),
        ),
        migrations.AlterField(
            model_name='book_cab_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 384100)),
        ),
        migrations.AlterField(
            model_name='book_cab_details',
            name='time_of_depature',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 383991), null=True),
        ),
        migrations.AlterField(
            model_name='bring_groceries',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 386181)),
        ),
        migrations.AlterField(
            model_name='bring_groceries',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 386250)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 388772)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 388842)),
        ),
        migrations.AlterField(
            model_name='cooking',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 382551)),
        ),
        migrations.AlterField(
            model_name='cooking',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 382617)),
        ),
        migrations.AlterField(
            model_name='faculty_service_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 381492)),
        ),
        migrations.AlterField(
            model_name='faculty_service_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 381559)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 377613)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 377673)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 377486)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 377523)),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 375731)),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 375798)),
        ),
        migrations.AlterField(
            model_name='laundry_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 380205)),
        ),
        migrations.AlterField(
            model_name='laundry_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 380331)),
        ),
        migrations.AlterField(
            model_name='medical_sevices',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 387501)),
        ),
        migrations.AlterField(
            model_name='medical_sevices',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 387599)),
        ),
        migrations.AlterField(
            model_name='notify_gate',
            name='date_of_arrival',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 385078)),
        ),
        migrations.AlterField(
            model_name='notify_gate',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 385168)),
        ),
        migrations.AlterField(
            model_name='notify_gate',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 385235)),
        ),
        migrations.AlterField(
            model_name='student_service_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 378738)),
        ),
        migrations.AlterField(
            model_name='student_service_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 378825)),
        ),
        migrations.AlterField(
            model_name='student_service_details',
            name='work_completed_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 378683)),
        ),
        migrations.AlterField(
            model_name='student_service_details',
            name='worker_assigned_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 378645)),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 350015)),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 350156)),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 374594)),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 374674)),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 391306)),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 391367)),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 391237)),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 44, 54, 391275)),
        ),
    ]
