# Generated by Django 2.1.3 on 2018-12-10 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0009_auto_20181210_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_visitor',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 684579)),
        ),
        migrations.AlterField(
            model_name='add_visitor',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 684649)),
        ),
        migrations.AlterField(
            model_name='attendence_tracker',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 698344)),
        ),
        migrations.AlterField(
            model_name='attendence_tracker',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 698386)),
        ),
        migrations.AlterField(
            model_name='attendence_tracker',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 698450)),
        ),
        migrations.AlterField(
            model_name='book_cab_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 692670)),
        ),
        migrations.AlterField(
            model_name='book_cab_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 692740)),
        ),
        migrations.AlterField(
            model_name='book_cab_details',
            name='time_of_depature',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 692622), null=True),
        ),
        migrations.AlterField(
            model_name='bring_groceries',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 695179)),
        ),
        migrations.AlterField(
            model_name='bring_groceries',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 695250)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 697441)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 697509)),
        ),
        migrations.AlterField(
            model_name='cooking',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 690760)),
        ),
        migrations.AlterField(
            model_name='cooking',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 690829)),
        ),
        migrations.AlterField(
            model_name='faculty_service_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 689618)),
        ),
        migrations.AlterField(
            model_name='faculty_service_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 689687)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 685547)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 685607)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 685418)),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 685457)),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 683360)),
        ),
        migrations.AlterField(
            model_name='in_out',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 683430)),
        ),
        migrations.AlterField(
            model_name='laundry_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 688345)),
        ),
        migrations.AlterField(
            model_name='laundry_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 688413)),
        ),
        migrations.AlterField(
            model_name='medical_sevices',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 696267)),
        ),
        migrations.AlterField(
            model_name='medical_sevices',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 696340)),
        ),
        migrations.AlterField(
            model_name='notify_gate',
            name='date_of_arrival',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 693680)),
        ),
        migrations.AlterField(
            model_name='notify_gate',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 693771)),
        ),
        migrations.AlterField(
            model_name='notify_gate',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 693837)),
        ),
        migrations.AlterField(
            model_name='student_service_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 686801)),
        ),
        migrations.AlterField(
            model_name='student_service_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 686861)),
        ),
        migrations.AlterField(
            model_name='student_service_details',
            name='work_completed_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 686747)),
        ),
        migrations.AlterField(
            model_name='student_service_details',
            name='worker_assigned_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 686708)),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 653467)),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 653548)),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 682082)),
        ),
        migrations.AlterField(
            model_name='worker_details',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 682211)),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='entry_created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 699295)),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='entry_last_modified_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 699355)),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 699224)),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 22, 46, 37, 699262)),
        ),
    ]
